{
  "swagger": "2.0",
  "info": {
    "title": "Tendocs Documents",
    "description": "A fast, simple, and capable service to automate the creation of Office documents based on text, images, documents and tables. More Information: https://www.tendocs.com",
    "contact": {
      "name": "Support",
      "url": "https://www.tendocs.com",
      "email": "support@tendocs.com"
    },
    "version": "v1"
  },
  "host": "api.tendocs.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "consumes": [],
  "produces": [],
  "paths": {
    "/documents/v1/template": {
      "post": {
        "tags": [
          "Documents",
          "Template",
          "Collaboration"
        ],
        "operationId": "V1DocumentTemplatePost",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DocumentTemplateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Office Template (Binary) File",
            "schema": {
              "format": "binary",
              "title": "Template File",
              "type": "string"
            }
          },
          "403": {
            "description": "The request is not authorized to make the template request"
          },
          "404": {
            "description": "Service has not been found, please contact support@tendocs.com"
          },
          "500": {
            "description": "Something has gone wrong, please contact support@tendocs.com"
          }
        },
        "summary": "Create New Document From Template",
        "description": "Create a new Office document by merging an office template with text, images, documents and tables."
      }
    },
    "/conversion/v1/convert": {
      "post": {
        "tags": [
          "Documents",
          "Conversion",
          "PDF"
        ],
        "operationId": "V1ConversionConvertPost",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ConversionConvertRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Binary File",
            "schema": {
              "format": "binary",
              "title": "File",
              "type": "string",
              "example": "[[Binary File]]"
            }
          },
          "403": {
            "description": "The request is not authorized to make the conversion request"
          },
          "404": {
            "description": "Service has not been found, please contact support@tendocs.com"
          },
          "500": {
            "description": "Something has gone wrong, please contact support@tendocs.com"
          }
        },
        "summary": "Convert a Document to PDF, HTML or TXT",
        "description": "Convert a document to a new file format. Includes PDF and HTML."
      }
    },
    "/ai/v1/tasks/summary": {
      "post": {
        "tags": [
          "Documents",
          "AI",
          "Summary"
        ],
        "operationId": "V1AiSummaryPost",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AiSummaryRequest"
            }
          }
        ],
        "responses": {
          "403": {
            "description": "The request is not authorized to make the conversion request"
          },
          "404": {
            "description": "Service has not been found, please contact support@tendocs.com"
          },
          "500": {
            "description": "Something has gone wrong, please contact support@tendocs.com"
          },
          "200": {
            "description": "default",
            "schema": {
              "type": "object",
              "properties": {
                "Type": {
                  "type": "string",
                  "example": "Summary"
                },
                "Content": {
                  "type": "string",
                  "example": "Summary of the document provided."
                },
                "Length": {
                  "type": "number",
                  "example": 300
                }
              },
              "required": [
                "Type",
                "Content",
                "Length"
              ]
            }
          }
        },
        "summary": "Summarise a document using AI",
        "description": "Create a AI (GPT-4) generated summary of the provided document."
      }
    },
    "/ai/v1/tasks/summary/result": {
      "get": {
        "responses": {
          "200": {
            "description": "default",
            "schema": {
              "type": "object",
              "properties": {
                "Type": {
                  "type": "string"
                },
                "Content": {
                  "type": "string"
                },
                "TargetWords": {
                  "type": "string"
                },
                "Length": {
                  "type": "number"
                }
              },
              "required": [
                "Type",
                "Content",
                "TargetWords",
                "Length"
              ]
            }
          }
        },
        "summary": "V1AiSummaryResult",
        "description": "Status of the summary call",
        "operationId": "V1AiSummaryResult",
        "x-ms-visibility": "internal",
        "parameters": [
          {
            "name": "runId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "threadId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ]
      }
    },
    "/ai/v1/tasks/compare": {
      "post": {
        "tags": [
          "Documents",
          "AI",
          "Compare"
        ],
        "operationId": "V1AiComparePost",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AiCompareRequest"
            }
          }
        ],
        "responses": {
          "403": {
            "description": "The request is not authorized to make the conversion request"
          },
          "404": {
            "description": "Service has not been found, please contact support@tendocs.com"
          },
          "500": {
            "description": "Something has gone wrong, please contact support@tendocs.com"
          },
          "200": {
            "description": "default",
            "schema": {
              "type": "object",
              "properties": {
                "differences": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "aspect": {
                        "type": "string"
                      },
                      "detailsummary": {
                        "type": "string"
                      },
                      "detail": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "Document": {
                              "type": "string"
                            },
                            "Summary": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "Document",
                            "Summary"
                          ]
                        }
                      },
                      "importance": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "aspect",
                      "detailsummary",
                      "detail",
                      "importance"
                    ]
                  }
                },
                "summary": {
                  "type": "string"
                }
              },
              "required": [
                "differences",
                "summary"
              ]
            }
          }
        },
        "summary": "Compare documents using AI",
        "description": "Create an AI (GPT-4) comparison of documents (contracts, reports, quotes, etc)."
      }
    },
    "/ai/v1/tasks/compare/result": {
      "get": {
        "responses": {
          "default": {
            "description": "default",
            "schema": {}
          }
        },
        "summary": "V1AiCompareResult",
        "description": "Result of the compare call",
        "operationId": "V1AiCompareResult",
        "x-ms-visibility": "internal",
        "parameters": [
          {
            "name": "runId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "threadId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ]
      }
    }
  },
  "definitions": {
    "DocumentTemplateRequest": {
      "required": [
        "template"
      ],
      "type": "object",
      "properties": {
        "template": {
          "type": "object",
          "required": [
            "file"
          ],
          "properties": {
            "file": {
              "format": "binary",
              "type": "string",
              "x-ms-visibility": "important",
              "x-ms-summary": "Template File",
              "description": "File Contents of the Office Document template."
            }
          },
          "example": {
            "$content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "$content": "UEsDBBQABgAIAAAAIQCqt...[[Base64 Encoded File]]"
          }
        },
        "images": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "file",
              "token"
            ],
            "properties": {
              "token": {
                "type": "string",
                "x-ms-summary": "Token",
                "description": "Document replacement token representing the image."
              },
              "file": {
                "type": "string",
                "x-ms-summary": "File Content",
                "description": "The file contents of an image.",
                "format": "binary"
              }
            }
          },
          "example": [
            {
              "token": "CompanyLogo",
              "file": {
                "$content-type": "image/png",
                "$content": "iVBORw0KGgoAAAANSUhE...[[Base64 Encoded File]]"
              }
            },
            {
              "token": "InvoiceToLogo",
              "file": {
                "$content-type": "image/png",
                "$content": "iVBORw0KGgoAAAANSUhEUgA...[[Base64 Encoded File]]"
              }
            }
          ],
          "x-ms-summary": "Image",
          "x-ms-visibility": "advanced"
        },
        "text": {
          "x-ms-visibility": "important",
          "x-ms-summary": "Text",
          "type": "object",
          "description": "Collection of document replacement tokens and associated replacement text.",
          "example": {
            "Title": "10docs",
            "CompanyName": "10docs",
            "CompanySlogan": "Delivering stuff you didn't expect",
            "InvoiceNumber": "9999999",
            "CompanyStreetAddress": "1 Documentation Road",
            "CompanyCity": "Small Town",
            "CompanyPostcode": "3455",
            "CompanyWebsite": "www.10docs.com",
            "InvoiceToName": "Joost van Hoorn",
            "InvoiceToCompany": "VIP Customer Ltd",
            "InvoiceToStreetAddress": "101 Client Office Road",
            "InvoiceToCity": "Big Town",
            "InvoiceToPostCode": "4533",
            "InvoiceDate": "2023-01-01",
            "InvoiceDescription": "Significant work done.",
            "InvoicePurchaseOrder": "PO 32423423",
            "Modified": "2023-10-24T14:48:26Z",
            "Created": "2023-08-24T08:17:36Z"
          }
        },
        "substituteDocuments": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "file",
              "token"
            ],
            "properties": {
              "token": {
                "type": "string",
                "x-ms-summary": "Token",
                "description": "Document replacement token representing a document."
              },
              "file": {
                "type": "string",
                "format": "binary",
                "x-ms-summary": "File Content",
                "description": "The file content of a document."
              }
            }
          },
          "example": [
            {
              "token": "TermsAndConditions",
              "file": {
                "$content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "$content": "UEsDBBQABgAIAAAAIQDbOn...[[Base64 Encoded File]]"
              }
            }
          ],
          "x-ms-summary": "Document",
          "x-ms-visibility": "advanced",
          "description": "Documents that can be replaced inside another document."
        },
        "tables": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "rows",
              "token"
            ],
            "properties": {
              "token": {
                "type": "string",
                "x-ms-summary": "Token",
                "description": "Document replacement token representing the table."
              },
              "rows": {
                "type": "object",
                "x-ms-summary": "Rows",
                "description": "An array representing the rows in the table."
              }
            }
          },
          "example": [
            {
              "Token": "InvoiceLines",
              "Rows": [
                {
                  "Title": "Line1",
                  "Description": "Line Item 1",
                  "Amount": 100
                },
                {
                  "Title": "Line 2",
                  "Description": "Line Item 2",
                  "Amount": 200
                },
                {
                  "Title": "Line 3",
                  "Description": "Line Item 3",
                  "Amount": 300
                }
              ]
            }
          ],
          "x-ms-summary": "Table",
          "x-ms-visibility": "advanced"
        },
        "configuration": {
          "type": "object",
          "properties": {
            "documentresponseformat": {
              "type": "string",
              "enum": [
                "Original",
                "PDF",
                "HTML"
              ],
              "description": "The format you would like the document to be converted to.",
              "x-ms-visibility": "advanced",
              "x-ms-summary": "Document Format"
            },
            "keys": {
              "type": "object",
              "description": "Advanced Configuration Settings (use only as instructed)",
              "x-ms-visibility": "advanced",
              "x-ms-summary": "Configuration Keys"
            }
          },
          "description": "Configuration Settings",
          "example": {
            "documentresponseformat": "PDF",
            "Keys": {
              "example_key1": "example_key_value1",
              "example_key2": "example_key_value2"
            }
          }
        }
      }
    },
    "ConversionConvertRequest": {
      "type": "object",
      "required": [
        "document",
        "configuration"
      ],
      "properties": {
        "document": {
          "type": "object",
          "required": [
            "file"
          ],
          "properties": {
            "file": {
              "format": "binary",
              "type": "string",
              "x-ms-visibility": "important",
              "x-ms-summary": "File",
              "description": "File to be converted."
            }
          },
          "example": {
            "$content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "$content": "UEsDBBQAAAgIAJMrVV...[[Base64 Encoded File]]"
          },
          "description": "File to be converted."
        },
        "configuration": {
          "type": "object",
          "required": [
            "documentresponseformat"
          ],
          "properties": {
            "documentresponseformat": {
              "type": "string",
              "enum": [
                "PDF",
                "HTML"
              ],
              "description": "The format you would like the document to be converted to.",
              "x-ms-visibility": "important",
              "x-ms-summary": "Document Format"
            },
            "keys": {
              "type": "object",
              "description": "Advanced Configuration Settings (use only as instructed)",
              "x-ms-visibility": "advanced",
              "x-ms-summary": "Configuration Keys"
            }
          },
          "example": {
            "documentresponseformat": "PDF",
            "Keys": {
              "example_key1": "example_key_value1",
              "example_key2": "example_key_value2"
            }
          },
          "description": "Configuration Settings"
        }
      }
    },
    "AiSummaryRequest": {
      "type": "object",
      "required": [
        "document",
        "configuration"
      ],
      "properties": {
        "document": {
          "type": "object",
          "required": [
            "file"
          ],
          "properties": {
            "file": {
              "format": "binary",
              "type": "string",
              "x-ms-visibility": "important",
              "x-ms-summary": "File",
              "description": "File to be summarised."
            }
          },
          "example": {
            "$content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "$content": "UEsDBBQAAAgIAJMrVV...[[Base64 Encoded File]]"
          },
          "description": "File to be summarised."
        },
        "configuration": {
          "type": "object",
          "required": [
            "targetwords"
          ],
          "properties": {
            "targetwords": {
              "type": "string",
              "enum": [
                "Miniature",
                "Small",
                "Medium",
                "Large",
                "Massive"
              ],
              "description": "An indication of how large you would like the summary to be.",
              "x-ms-visibility": "important",
              "x-ms-summary": "Word Count"
            },
            "keys": {
              "type": "object",
              "description": "Advanced Configuration Settings (use only as instructed)",
              "x-ms-visibility": "advanced",
              "x-ms-summary": "Configuration Keys"
            }
          },
          "example": {
            "MaximumWordCount": 300,
            "Keys": {
              "example_key1": "example_key_value1",
              "example_key2": "example_key_value2"
            }
          },
          "description": "Configuration Settings"
        }
      }
    },
    "AiCompareRequest": {
      "type": "object",
      "required": [
        "comparisondocument",
        "sourcedocument",
        "configuration"
      ],
      "properties": {
        "sourcedocument": {
          "type": "object",
          "required": [
            "file"
          ],
          "properties": {
            "file": {
              "format": "binary",
              "type": "string",
              "x-ms-visibility": "important",
              "x-ms-summary": "File",
              "description": "First file to be compared."
            }
          },
          "example": {
            "$content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "$content": "UEsDBBQAAAgIAJMrVV...[[Base64 Encoded File]]"
          },
          "description": "File to be summarised."
        },
        "comparisondocument": {
          "type": "object",
          "required": [
            "file"
          ],
          "properties": {
            "file": {
              "format": "binary",
              "type": "string",
              "x-ms-visibility": "important",
              "x-ms-summary": "File",
              "description": "Second file to be compared"
            }
          },
          "example": {
            "$content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "$content": "UEsDBBQAAAgIAJMrVV...[[Base64 Encoded File]]"
          },
          "description": "File to be summarised."
        },
        "configuration": {
          "type": "object",
          "required": [
            "profession"
          ],
          "properties": {
            "profession": {
              "type": "string",
              "enum": [
                "Doctor",
                "Editor",
                "Lawyer",
                "General"
              ],
              "description": "The profession who would best be able to compare the documents.",
              "x-ms-visibility": "advanced",
              "x-ms-summary": "Document Format"
            },
            "keys": {
              "type": "object",
              "description": "Advanced Configuration Settings (use only as instructed)",
              "x-ms-visibility": "advanced",
              "x-ms-summary": "Configuration Keys"
            }
          },
          "example": {
            "profession": "Lawyer",
            "Keys": {
              "example_key1": "example_key_value1",
              "example_key2": "example_key_value2"
            }
          },
          "description": "Configuration Settings"
        }
      }
    }
  },
  "parameters": {},
  "responses": {},
  "securityDefinitions": {
    "API Key": {
      "type": "apiKey",
      "in": "header",
      "name": "X-API-KEY"
    }
  },
  "security": [
    {
      "API Key": []
    }
  ],
  "tags": [],
  "x-ms-connector-metadata": [
    {
      "propertyName": "Website",
      "propertyValue": "https://www.tendocs.com"
    },
    {
      "propertyName": "Privacy policy",
      "propertyValue": "https://www.tendocs.com/privacy"
    },
    {
      "propertyName": "Categories",
      "propertyValue": "Productivity;Content and Files"
    }
  ]
}