{
  "swagger": "2.0",
  "info": {
    "title": "Sparse Power Box Tools",
    "version": "1.0",
    "description": "Introducing the Sparse Power Box Tools. This connector gives Low-Code developers a set of tools to enhance your Power Platform capabilites. With these powerful tools you can build custom apps and automate workflows with ease.",
    "contact": {
      "name": "Sparse Support",
      "url": "https://sparsedevelopment.nl/en/",
      "email": "service@sparse.dev"
    }
  },  
  "x-ms-connector-metadata": [
    {
      "propertyName": "Website",
      "propertyValue": "https://sparsedevelopment.nl/en/"
    },
    {
      "propertyName": "Privacy policy",
      "propertyValue": "https://sparsedevelopment.nl/en/privacy-policy/"
    },
    {
      "propertyName": "Categories",
      "propertyValue": "Content and Files;Data"
    }
  ],
  "host": "api.powerbox.bysparse.dev",
  "basePath": "/connector/pa/tools",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "apiKeyHeader": {
      "type": "apiKey",
      "name": "Sparse-Key",
      "in": "header"
    },
    "apiKeyQuery": {
      "type": "apiKey",
      "name": "sparse-key",
      "in": "query"
    }
  },
  "security": [
    {
      "apiKeyHeader": []
    },
    {
      "apiKeyQuery": []
    }
  ],
  "paths": {
    "/pdf/stamp/image": {
      "post": {
        "description": "Add custom stamps to your PDF files.",
        "operationId": "pdf-stamp-image",
        "summary": "Add image stamp to PDF",
        "tags": [
          "document",
          "pdf"
        ],
        "parameters": [
          {
            "name": "req-pdf-stamp-image",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-pdf-stamp-image"
            },
            "description": "Contains the PDF and the image"
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Succesfully added a stamp on the PDF file.",
            "schema": {
              "$ref": "#/definitions/resp-200-pdf-stamp-image"
            },
            "examples": {
              "application/json": {
                "result": "base64"
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/excel/sheet/add-rows": {
      "post": {
        "description": "Easily add multiple rows to an existing Excel file.",
        "operationId": "excel-sheet-add-rows",
        "summary": "Add rows to Excel",
        "tags": [
          "document",
          "excel"
        ],
        "parameters": [
          {
            "name": "req-excel-sheet-addrows",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-excel-sheet-addrows"
            }
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Succesfully added rows to the provided Excel sheet",
            "schema": {
              "$ref": "#/definitions/resp-200-excel-sheet-add-rows"
            },
            "examples": {
              "application/json": {
                "result": "string"
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/pdf/create/by-html": {
      "post": {
        "description": "An HTML file (.html) is converted into a PDF file.",
        "operationId": "pdf-create-by-html",
        "summary": "Convert HTML to PDF",
        "tags": [
          "document",
          "pdf"
        ],
        "parameters": [
          {
            "name": "req-pdf-create-by-html",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-pdf-create-by-html"
            },
            "description": "Content and data"
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Succesfully created a new PDF file based on provided HTML and data.",
            "schema": {
              "$ref": "#/definitions/resp-200-pdf-create-by-html"
            },
            "examples": {
              "application/json": {
                "result": "string"
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/image/merge/drawing": {
      "post": {
        "description": "Makes it easy to merge images together.",
        "operationId": "image-merge-drawing",
        "summary": "Merge images",
        "tags": [
          "image"
        ],
        "parameters": [
          {
            "name": "req-image-merge-drawing",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-image-merge-drawing"
            },
            "description": "The background and the image that will be merged"
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Succesfully merged the image on the background",
            "schema": {
              "$ref": "#/definitions/resp-200-image-merge-drawing"
            },
            "examples": {
              "application/json": {
                "result": "base64"
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/pdf/stamp/text": {
      "post": {
        "description": "Add a text as a stamp to a PDF file.",
        "operationId": "pdf-stamp-text",
        "summary": "Add text stamp to PDF",
        "tags": [
          "pdf",
          "document"
        ],
        "parameters": [
          {
            "name": "req-pdf-stamp-text",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-pdf-stamp-text"
            },
            "description": "Contains PDF and text"
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Succesfully added a stamp on the PDF file.",
            "schema": {
              "$ref": "#/definitions/resp-200-pdf-stamp-text"
            },
            "examples": {
              "application/json": {
                "result": "base64"
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/csv/to-json": {
      "post": {
        "description": "This powerful tool allows users to convert CSV files to JSON data.",
        "operationId": "csv-to-json",
        "summary": "Convert CSV to JSON",
        "tags": [
          "document",
          "csv"
        ],
        "parameters": [
          {
            "name": "req-csv-to-json",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-csv-to-json"
            }
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Succesfully converted the provided CSV file to JSON-objects",
            "schema": {
              "$ref": "#/definitions/resp-200-csv-to-json"
            },
            "examples": {
              "application/json": {
                "records": []
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/pdf/create/by-url": {
      "post": {
        "description": "Easily save a website url as a PDF file.",
        "operationId": "pdf-create-by-url",
        "summary": "Convert URL to PDF",
        "tags": [
          "document",
          "pdf"
        ],
        "parameters": [
          {
            "name": "req-pdf-create-by-url",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-pdf-create-by-url"
            },
            "description": "Contains the url that will be converted"
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Succesfully created a new PDF file based on provided url.",
            "schema": {
              "$ref": "#/definitions/resp-200-pdf-create-by-url"
            },
            "examples": {
              "application/json": {
                "result": "base64"
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/image/stamp/text": {
      "post": {
        "description": "Add a text stamp to an image.",
        "operationId": "image-stamp-text",
        "summary": "Add text stamp to image",
        "parameters": [
          {
            "name": "req-image-stamp-text",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-image-stamp-text"
            }
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/resp-200-image-stamp-text"
            },
            "examples": {
              "application/json": {
                "result": ""
              }
            }
          },
          "400": {
            "description": ""
          }
        }
      }
    },
    "/image/resize": {
      "post": {
        "description": "Resize Image",
        "operationId": "image-resize",
        "summary": "Resize Image",
        "parameters": [
          {
            "name": "req-image-resize",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-image-resize"
            }
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/resp-200-image-resize"
            },
            "examples": {
              "application/json": {
                "result": ""
              }
            }
          },
          "400": {
            "description": ""
          }
        }
      }
    },
    "/pdf/split/by-page": {
      "post": {
        "description": "Easily split a PDF file into multiple PDF files.",
        "operationId": "pdf-split-by-page",
        "summary": "Slit PDF",
        "parameters": [
          {
            "name": "req-pdf-split-by-page",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-pdf-split-by-page"
            }
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/resp-200-pdf-split-by-page"
            },
            "examples": {
              "application/json": {
                "results": [
                  ""
                ]
              }
            }
          }
        }
      }
    },
    "/image/stamp/exif": {
      "post": {
        "description": "Add EXIF tags to an image",
        "operationId": "image-stamp-exif",
        "summary": "Add EXIF information to an image",
        "parameters": [
          {
            "name": "req-image-stamp-exif",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-image-stamp-exif"
            }
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/resp-200-image-stamp-exif"
            },
            "examples": {
              "application/json": {
                "result": "base64",
                "printedTags": [
                  ""
                ]
              }
            }
          }
        }
      }
    },
    "/form/fill": {
      "post": {
        "description": "Populates the PDF Form provided with the JSON form data provided.",
        "operationId": "pdf-fill-form",
        "summary": "Fill a PDF form",
        "parameters": [
          {
            "name": "req-pdf-fill-form",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-pdf-fill-form"
            }
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "The processed PDF form (Base64)",
            "schema": {
              "$ref": "#/definitions/resp-200-pdf-fill-form"
            },
            "examples": {
              "application/json": {
                "result": "string"
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/form/getdata": {
      "post": {
        "description": "Extracts data from a filled in PDF file and returns the data in JSON format allowing further actions.",
        "operationId": "pdf-get-form-data",
        "summary": "Get PDF form data",
        "parameters": [
          {
            "name": "req-pdf-get-form-data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/req-pdf-get-form-data"
            },
            "description": " A Base64 encoded representation of the PDF file."
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": " The data extracted from the form in JSON format.",
            "schema": {
              "$ref": "#/definitions/resp-200-pdf-get-form-data"
            },
            "examples": {
              "application/json": {
                "result": {}
              }
            }
          },
          "400": {
            "description": "Invalid data supplied"
          }
        }
      }
    },
    "/pdf/merge/simple": {
        "post": {
            "description": "Merge multiple pdf files ",
            "operationId": "pdf-merge-simple",
            "summary": "Merge a set of PDF files to one PDF (Simple)",
            "parameters": [
                {
                    "name": "req-pdf-merge-simple",
                    "in": "body",
                    "schema": {
                        "$ref": "#/definitions/req-pdf-merge-simple"
                    }
                }
            ],
            "consumes": [
                "application/json"
            ],
            "produces": [
                "application/json"
            ],
            "responses": {
                "200": {
                    "description": "",
                    "schema": {
                        "$ref": "#/definitions/resp-200-pdf-merge-simple"
                    },
                    "examples": {
                        "application/json": {
                            "result": "string"
                        }
                    }
                },
                "400": {
                    "description": "Invalid data supplied"
                }
            }
        }
    }
  },
  "definitions": {
    "req-excel-sheet-addrows": {
      "required": [
        "sheet",
        "excelFile"
      ],
      "type": "object",
      "properties": {
        "sheet": {
          "title": "Sheetname",
          "description": "Name of the sheet",
          "type": "string",
          "x-ms-summary": "Sheetname",
          "x-ms-visibility": ""
        },
        "data": {
          "title": "Data",
          "description": "Array of JSON objects. Could be anything",
          "type": "array",
          "items": {
            "type": "object"
          },
          "x-ms-summary": "Data",
          "x-ms-visibility": ""
        },
        "excelFile": {
          "format": "byte",
          "title": "Excel",
          "description": "Excel file",
          "type": "string",
          "x-ms-summary": "Excel",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "sheet": "Test",
        "data": [],
        "excelFile": "base64"
      }
    },
    "req-pdf-stamp-text": {
      "required": [
        "pdf",
        "text"
      ],
      "type": "object",
      "properties": {
        "pdf": {
          "format": "byte",
          "title": "PDF",
          "description": "PDF file",
          "type": "string",
          "x-ms-summary": "PDF",
          "x-ms-visibility": ""
        },
        "text": {
          "title": "Text",
          "description": "Text that will be stamped",
          "type": "string",
          "x-ms-summary": "Text",
          "x-ms-visibility": ""
        },
        "options": {
          "type": "object",
          "properties": {
            "color": {
              "title": "Font Color",
              "description": "Color of the font",
              "default": "#000000",
              "type": "string",
              "x-ms-summary": "Font Color",
              "x-ms-visibility": "advanced"
            },
            "size": {
              "title": "Font Size",
              "description": "Size of the font",
              "default": "50",
              "type": "integer",
              "x-ms-summary": "Font Size",
              "x-ms-visibility": "advanced"
            },
            "rotate": {
              "title": "Rotate",
              "description": "Rotate the text with degrees",
              "default": "0",
              "type": "integer",
              "x-ms-summary": "Rotate",
              "x-ms-visibility": "advanced"
            },
            "position": {
              "type": "object",
              "properties": {
                "yOffset": {
                  "title": "Y-Offset",
                  "description": "Y-Offset",
                  "default": "25",
                  "type": "integer",
                  "x-ms-summary": "Y-Offset",
                  "x-ms-visibility": "advanced"
                },
                "yOffsetStart": {
                  "title": "Start of Y-Offset",
                  "description": "Start of Y-Offset bottom or top",
                  "default": "bottom",
                  "type": "string",
                  "x-ms-summary": "Start of Y-Offset",
                  "x-ms-visibility": "advanced"
                },
                "xOffset": {
                  "title": "X-Offset",
                  "description": "X-Offset",
                  "default": "50",
                  "type": "integer",
                  "x-ms-summary": "X-Offset",
                  "x-ms-visibility": "advanced"
                }
              }
            }
          }
        }
      },
      "example": {
        "pdf": "base64",
        "text": "value",
        "options": {
          "color": "#000000",
          "size": 50,
          "rotate": 0,
          "position": {
            "yOffset": 25,
            "yOffsetStart": "bottom",
            "xOffset": 50
          }
        }
      }
    },
    "req-pdf-create-by-url": {
      "required": [
        "url"
      ],
      "type": "object",
      "properties": {
        "url": {
          "title": "Url",
          "description": "A valid url",
          "type": "string",
          "x-ms-summary": "HTML",
          "x-ms-visibility": ""
        },
        "options": {
          "type": "object",
          "properties": {
            "mediaType": {
              "title": "MediaType",
              "description": "MediaType when printing HTML to PDF",
              "default": "print",
              "type": "string",
              "x-ms-summary": "MediaType",
              "x-ms-visibility": "advanced"
            },
            "format": {
              "title": "Page format",
              "description": "Page format of the PDF. Can be A4, A5 or A3",
              "default": "A4",
              "type": "string",
              "x-ms-summary": "Page format",
              "x-ms-visibility": "advanced"
            },
            "landscape": {
              "title": "Landscape",
              "description": "Print landscape or portrait",
              "default": "false",
              "type": "boolean",
              "x-ms-summary": "Landscape",
              "x-ms-visibility": "advanced"
            },
            "printBackground": {
              "type": "boolean",
              "x-ms-visibility": "internal"
            },
            "margin": {
              "type": "object",
              "properties": {
                "left": {
                  "title": "Margin Left",
                  "description": "Margin Left",
                  "default": "0px",
                  "type": "string",
                  "x-ms-summary": "Margin Left",
                  "x-ms-visibility": "advanced"
                },
                "right": {
                  "title": "Margin Right",
                  "description": "Margin Right",
                  "default": "0px",
                  "type": "string",
                  "x-ms-summary": "Margin Right",
                  "x-ms-visibility": "advanced"
                },
                "top": {
                  "title": "Margin Top",
                  "description": "Margin Top",
                  "default": "0px",
                  "type": "string",
                  "x-ms-summary": "Margin Top",
                  "x-ms-visibility": "advanced"
                },
                "bottom": {
                  "title": "Margin Bottom",
                  "description": "Margin Bottom",
                  "default": "0px",
                  "type": "string",
                  "x-ms-summary": "Margin Bottom",
                  "x-ms-visibility": "advanced"
                }
              }
            }
          }
        }
      },
      "example": {
        "url": "https://sparse.dev",
        "options": {
          "mediaType": "print",
          "format": "A4",
          "landscape": false,
          "printBackground": true,
          "margin": {
            "left": "0px",
            "right": "0px",
            "top": "0px",
            "bottom": "0px"
          }
        }
      }
    },
    "req-pdf-create-by-html": {
      "required": [
        "content"
      ],
      "type": "object",
      "properties": {
        "content": {
          "title": "HTML",
          "description": "A valid HTML string. Use {{ property }} from data-property to replace values in HTML string with Liquid.",
          "type": "string",
          "x-ms-summary": "HTML",
          "x-ms-visibility": ""
        },
        "data": {
          "title": "Data",
          "description": "Can be a JSON object. Use {{ property }} from data-property to replace values in HTML string with Liquid.",
          "type": "object",
          "x-ms-summary": "Data",
          "x-ms-visibility": ""
        },
        "options": {
          "type": "object",
          "properties": {
            "mediaType": {
              "title": "MediaType",
              "description": "MediaType when printing HTML to PDF",
              "default": "print",
              "type": "string",
              "x-ms-summary": "MediaType",
              "x-ms-visibility": "advanced"
            },
            "format": {
              "title": "Page format",
              "description": "Page Format of the PDF. Can be A4, A5 or A3",
              "default": "A4",
              "type": "string",
              "x-ms-summary": "Page format",
              "x-ms-visibility": "advanced"
            },
            "landscape": {
              "title": "Landscape",
              "description": "Print landscape or portrait",
              "default": "false",
              "type": "boolean",
              "x-ms-summary": "Landscape",
              "x-ms-visibility": "advanced"
            },
            "printBackground": {
              "type": "boolean",
              "x-ms-visibility": "internal"
            },
            "margin": {
              "type": "object",
              "properties": {
                "left": {
                  "title": "Margin Left",
                  "description": "Margin Left",
                  "default": "0px",
                  "type": "string",
                  "x-ms-summary": "Margin Left",
                  "x-ms-visibility": "advanced"
                },
                "right": {
                  "title": "Margin Right",
                  "description": "Margin Right",
                  "default": "0px",
                  "type": "string",
                  "x-ms-summary": "Margin Right",
                  "x-ms-visibility": "advanced"
                },
                "top": {
                  "title": "Margin Top",
                  "description": "Margin Top",
                  "default": "0px",
                  "type": "string",
                  "x-ms-summary": "Margin Top",
                  "x-ms-visibility": "advanced"
                },
                "bottom": {
                  "title": "Margin Bottom",
                  "description": "Margin Bottom",
                  "default": "0px",
                  "type": "string",
                  "x-ms-summary": "Margin Bottom",
                  "x-ms-visibility": "advanced"
                }
              }
            }
          }
        }
      },
      "example": {
        "content": "<h1>Sparse HTML to PDF<h1>",
        "data": {},
        "options": {
          "mediaType": "print",
          "format": "A4",
          "landscape": false,
          "printBackground": true,
          "margin": {
            "left": "0px",
            "right": "0px",
            "top": "0px",
            "bottom": "0px"
          }
        }
      }
    },
    "resp-200-image-merge-drawing": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "Merged Image",
          "description": "Merged image with background and drawing",
          "type": "string",
          "x-ms-summary": "Image",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "result": "base64"
      }
    },
    "req-csv-to-json": {
      "description": "csvfile",
      "required": [
        "csv",
        "options"
      ],
      "type": "object",
      "properties": {
        "csv": {
          "format": "byte",
          "title": "CSV",
          "description": "Comma seperated values (CSV) file",
          "type": "string",
          "x-ms-summary": "CSV",
          "x-ms-visibility": ""
        },
        "options": {
          "required": [
            "hasHeaders",
            "delimiter"
          ],
          "type": "object",
          "properties": {
            "hasHeaders": {
              "title": "Has headers",
              "description": "Does the first row contain headers",
              "default": "true",
              "type": "boolean",
              "x-ms-summary": "Has headers",
              "x-ms-visibility": "advanced"
            },
            "delimiter": {
              "title": "Delimiter",
              "description": "Delimiter for splitting values",
              "default": ",",
              "type": "string",
              "x-ms-summary": "Delimiter",
              "x-ms-visibility": "advanced"
            }
          }
        }
      },
      "example": {
        "options": {
          "hasHeaders": true,
          "delimiter": "string"
        },
        "csv": "string"
      }
    },
    "req-image-merge-drawing": {
      "required": [
        "background",
        "drawing"
      ],
      "type": "object",
      "properties": {
        "background": {
          "format": "byte",
          "title": "Background",
          "description": "Background image",
          "type": "string",
          "x-ms-summary": "Background",
          "x-ms-visibility": ""
        },
        "drawing": {
          "format": "byte",
          "title": "Drawing",
          "description": "Drawing image (should have transparent background)",
          "type": "string",
          "x-ms-summary": "Drawing",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "background": "base64",
        "drawing": "base64"
      }
    },
    "resp-200-csv-to-json": {
      "type": "object",
      "properties": {
        "records": {
          "title": "Records",
          "description": "Records from CSV",
          "type": "array",
          "items": {
            "type": "object"
          },
          "x-ms-summary": "Records",
          "x-ms-visibility": ""
        }
      }
    },
    "req-pdf-stamp-image": {
      "required": [
        "pdf",
        "image"
      ],
      "type": "object",
      "properties": {
        "pdf": {
          "format": "byte",
          "title": "PDF",
          "description": "PDF file",
          "type": "string",
          "x-ms-summary": "PDF",
          "x-ms-visibility": ""
        },
        "image": {
          "format": "byte",
          "title": "Image",
          "description": "Image that will be stamped",
          "type": "string",
          "x-ms-summary": "Image",
          "x-ms-visibility": ""
        },
        "options": {
          "type": "object",
          "properties": {
            "opacity": {
              "title": "Opacity",
              "description": "Adjust the scale of the image",
              "default": "1",
              "type": "number",
              "x-ms-summary": "Opacity",
              "x-ms-visibility": "advanced"
            },
            "scale": {
              "title": "Scale",
              "description": "Adjust the scale of the image",
              "default": "1",
              "type": "number",
              "x-ms-summary": "Scale",
              "x-ms-visibility": "advanced"
            },
            "rotate": {
              "title": "Rotate",
              "description": "Rotate the image with degrees",
              "default": "0",
              "type": "integer",
              "x-ms-summary": "Rotate",
              "x-ms-visibility": "advanced"
            },
            "position": {
              "type": "object",
              "properties": {
                "yOffset": {
                  "title": "Y-Offset",
                  "description": "Y-Offset",
                  "default": "25",
                  "type": "integer",
                  "x-ms-summary": "Y-Offset",
                  "x-ms-visibility": "advanced"
                },
                "yOffsetStart": {
                  "title": "Start of Y-Offset",
                  "description": "Start of Y-Offset bottom or top",
                  "default": "bottom",
                  "type": "string",
                  "x-ms-summary": "Start of Y-Offset",
                  "x-ms-visibility": "advanced"
                },
                "xOffset": {
                  "title": "X-Offset",
                  "description": "X-Offset",
                  "default": "50",
                  "type": "integer",
                  "x-ms-summary": "X-Offset",
                  "x-ms-visibility": "advanced"
                }
              }
            }
          }
        }
      },
      "example": {
        "pdf": "base64",
        "image": "base64",
        "options": {
          "scale": 1,
          "rotate": 0,
          "position": {
            "yOffset": 25,
            "yOffsetStart": "bottom",
            "xOffset": 50
          }
        }
      }
    },
    "resp-200-image-resize": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "Resized image",
          "description": "Resized image",
          "type": "string",
          "x-ms-summary": "Resized image",
          "x-ms-visibility": ""
        }
      }
    },
    "req-image-stamp-text": {
      "type": "object",
      "properties": {
        "image": {
          "format": "byte",
          "title": "Image",
          "description": "Image",
          "type": "string",
          "x-ms-summary": "Image",
          "x-ms-visibility": ""
        },
        "text": {
          "title": "Text to Stamp",
          "description": "Text to Stamp",
          "type": "string",
          "x-ms-summary": "Text to Stamp",
          "x-ms-visibility": ""
        },
        "options": {
          "type": "object",
          "properties": {
            "location": {
              "title": "Location of the stamp",
              "description": "Location of the stamp",
              "default": "Center",
              "type": "string",
              "x-ms-summary": "Location of the stamp",
              "x-ms-visibility": "advanced"
            },
            "fontColor": {
              "title": "Fontcolor",
              "description": "Fontcolor",
              "default": "#ffffff",
              "type": "string",
              "x-ms-summary": "Fontcolor",
              "x-ms-visibility": "advanced"
            },
            "fontSize": {
              "title": "Fontsize",
              "description": "Fontsize",
              "default": "25",
              "type": "integer",
              "x-ms-summary": "Fontsize",
              "x-ms-visibility": "advanced"
            }
          }
        }
      },
      "example": {
        "image": "string",
        "text": "string",
        "options": {
          "location": "Center",
          "fontColor": "#ffffff",
          "fontSize": 50
        }
      }
    },
    "resp-200-image-stamp-text": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "Stamped image",
          "description": "Stamped image",
          "type": "string",
          "x-ms-summary": "Stamped image",
          "x-ms-visibility": ""
        }
      }
    },
    "resp-200-pdf-split-by-page": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "format": "byte",
            "type": "string"
          },
          "title": "PDF-file",
          "description": "PDF-file",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        }
      }
    },
    "resp-200-image-stamp-exif": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "Stamped image",
          "description": "Stamped image",
          "type": "string",
          "x-ms-summary": "Stamped image",
          "x-ms-visibility": ""
        },
        "printedTags": {
          "title": "Printed Tags",
          "description": "Printed Tags",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-ms-summary": "Printed Tags",
          "x-ms-visibility": "advanced"
        }
      }
    },
    "req-image-stamp-exif": {
      "type": "object",
      "properties": {
        "image": {
          "format": "byte",
          "title": "Image",
          "description": "Image",
          "type": "string",
          "x-ms-summary": "Image",
          "x-ms-visibility": ""
        },
        "options": {
          "type": "object",
          "properties": {
            "tags": {
              "title": "Tags",
              "description": "Tags",
              "type": "array",
              "items": {
                "type": "string"
              },
              "x-ms-summary": "Tags",
              "x-ms-visibility": "advanced"
            },
            "location": {
              "title": "Location of the stamp",
              "description": "Location of the stamp",
              "default": "Center",
              "type": "string",
              "x-ms-summary": "Location of the stamp",
              "x-ms-visibility": "advanced"
            },
            "fontColor": {
              "title": "Fontcolor",
              "description": "Fontcolor",
              "default": "#ffffff",
              "type": "string",
              "x-ms-summary": "Fontcolor",
              "x-ms-visibility": "advanced"
            },
            "fontSize": {
              "title": "Fontsize",
              "description": "Fontsize",
              "default": "25",
              "type": "integer",
              "x-ms-summary": "Fontsize",
              "x-ms-visibility": "advanced"
            },
            "printTagName": {
              "title": "Print TagName",
              "description": "Print TagName",
              "default": "false",
              "type": "boolean",
              "x-ms-summary": "Print TagName",
              "x-ms-visibility": "advanced"
            }
          }
        }
      },
      "example": {
        "image": "string",
        "options": {
          "tags": [],
          "location": "Center",
          "fontColor": "#ffffff",
          "fontSize": 50,
          "showTagName": true
        }
      }
    },
    "req-pdf-split-by-page": {
      "type": "object",
      "properties": {
        "pdf": {
          "format": "byte",
          "title": "PDF-file",
          "description": "PDF-file",
          "type": "string",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        },
        "options": {
          "type": "object",
          "properties": {
            "numberOfPages": {
              "title": "Number of Pages",
              "description": "Splits PDF documents by the number of pages specified.",
              "default": "1",
              "type": "number",
              "x-ms-summary": "Number of Pages",
              "x-ms-visibility": "advanced"
            }
          }
        }
      },
      "example": {
        "pdf": "base64",
        "options": {
          "numberOfPages": 1
        }
      }
    },
    "req-image-resize": {
      "type": "object",
      "properties": {
        "image": {
          "format": "byte",
          "title": "Image",
          "description": "Image",
          "type": "string",
          "x-ms-summary": "Image",
          "x-ms-visibility": ""
        },
        "width": {
          "title": "Width",
          "description": "Width of the image",
          "type": "integer",
          "x-ms-summary": "Width",
          "x-ms-visibility": ""
        },
        "height": {
          "title": "Height",
          "description": "Height of the image",
          "type": "integer",
          "x-ms-summary": "Height",
          "x-ms-visibility": ""
        },
        "options": {
          "type": "object",
          "properties": {
            "ignoreAspectRation": {
              "title": "Ignore the Aspect Ration",
              "description": "Ignore the Aspect Ration",
              "default": "false",
              "type": "boolean",
              "x-ms-summary": "Ignore the Aspect Ration",
              "x-ms-visibility": ""
            }
          }
        }
      },
      "example": {
        "image": "string",
        "width": 0,
        "height": 0,
        "options": {
          "ignoreAspectRation": true
        }
      }
    },
    "req-pdf-fill-form": {
      "type": "object",
      "properties": {
        "pdf": {
          "format": "byte",
          "title": "PDF-file",
          "description": "PDF-file with form",
          "type": "string",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        },
        "data": {
          "title": "Data",
          "description": "Can be a JSON object.The data-property must match to the name of the element you want to fill in form.",
          "type": "object",
          "x-ms-summary": "Data",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "pdf": "string",
        "data": {}
      }
    },
    "req-pdf-get-form-data": {
      "type": "object",
      "properties": {
        "pdf": {
          "format": "byte",
          "title": "PDF-file",
          "description": "PDF-file with form",
          "type": "string",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "pdf": "string"
      }
    },
    "resp-200-pdf-stamp-text": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "PDF-file",
          "description": "PDf-file with stamped text",
          "type": "string",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "result": "base64"
      }
    },
    "resp-200-pdf-stamp-image": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "PDF-file",
          "description": "PDf-file with stamped image",
          "type": "string",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "result": "base64"
      }
    },
    "resp-200-pdf-create-by-url": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "PDF-file",
          "description": "Created PDF-file",
          "type": "string",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "result": "base64"
      }
    },
    "resp-200-pdf-create-by-html": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "PDF-file",
          "description": "Created PDF-file",
          "type": "string",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        }
      }
    },
    "resp-200-pdf-get-form-data": {
      "type": "object",
      "properties": {
        "result": {
          "title": "Form Data",
          "description": "A JSON object. The properties of the JSON object references the name of the field of the form in the PDF",
          "type": "object",
          "x-ms-summary": "Form Data",
          "x-ms-visibility": ""
        }
      },
      "example": {
        "result": {}
      }
    },
    "resp-200-excel-sheet-add-rows": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "Excel-sheet",
          "description": "Excel-sheet with added rows",
          "type": "string",
          "x-ms-summary": "Excel-sheet",
          "x-ms-visibility": ""
        }
      }
    },
    "resp-200-pdf-fill-form": {
      "type": "object",
      "properties": {
        "result": {
          "format": "byte",
          "title": "PDF-file",
          "description": "PDF-file with filled form",
          "type": "string",
          "x-ms-summary": "PDF-file",
          "x-ms-visibility": ""
        }
      }
    },
    "req-pdf-merge-simple": {
        "type": "object",
        "properties": {
            "pdfs": {
              "type": "array",
              "items": {
                "format": "byte",
                "type": "string"
              },
              "x-ms-visibility": "",
              "x-ms-summary": "PDF-file",
              "title": "PDF-file",
              "description": "PDF-file"
            }
        },
        "example": {
            "pdfs": [
                "string"
            ]
        }
    },
    "resp-200-pdf-merge-simple": {
        "type": "object",
        "properties": {
            "result": {
              "format": "byte",
              "title": "PDF-file",
              "description": "PDF-file from merged PDF-files",
              "type": "string",
              "x-ms-summary": "PDF-file",
              "x-ms-visibility": ""
            }
        }
    }
  },
  "tags": []
}