{
  "swagger": "2.0",
  "info": {
    "title": "Softools",
    "version": "1.0",
    "description": "Softools is a web-based application platform where off-the-shelf and custom apps can be designed, built and deployed in hours.",
    "contact": {
      "name": "Softools Support",
      "url": "https://support.softools.net",
      "email": "support@softools.net"
    }
  },
  "host": "api-gateway.softools.net",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "consumes": [],
  "produces": [],
  "paths": {
    "/Api/Apps/{AppIdentifier}/Data/{RecordID}": {
      "get": {
        "description": "Gets a record",
        "operationId": "Get-record",
        "summary": "Get a Record",
        "tags": [
          "Data"
        ],
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App, can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "RecordID",
            "in": "path",
            "description": "Identifier of the record",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier of the record",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "The tenant can be obtained from your system administrator",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response also includes all record data with field identifier as key",
            "schema": {
              "$ref": "#/definitions/Record-Response"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      },
      "delete": {
        "description": "Archive a record. Call this before delete.",
        "operationId": "Archive-record",
        "summary": "Archive a record",
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App, can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "RecordID",
            "in": "path",
            "description": "Identifier of the record",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier of the record",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "The tenant can be obtained from your system administrator",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response also includes all record data with field identifier as key",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      },
      "patch": {
        "description": "The Softools Api caters for Delta updates, meaning you can send only the changes which are relevant and not the entire document per PATCH request.\n",
        "operationId": "Patch-a-record",
        "summary": "Patch a Record",
        "tags": [
          "Data"
        ],
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App. Can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "RecordID",
            "in": "path",
            "description": "Id of the record",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier of the record",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "The tenant can be obtained from your system administrator",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "update-record",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Update-record"
            },
            "description": "Payload of this request is a JSON object containing all the updated field values with their key being the field identifier."
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response contains the record object",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      }
    },
    "/Api/Apps/{AppIdentifier}/Data/Report/{ReportID}": {
      "get": {
        "description": "Gets a list of records from report, limited to 250 records per request.\nOnly returns report field data.\nCan iterate using $top and $skip",
        "operationId": "Get-report-records",
        "summary": "Get report records",
        "tags": [
          "Data",
          "Report"
        ],
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App, can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "ReportID",
            "in": "path",
            "description": "Id of report\n\n",
            "required": true,
            "type": "number",
            "x-ms-summary": "Identifier of the record",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "$skip",
            "in": "query",
            "description": "Skips records, setting to 1 will return the second record",
            "type": "number",
            "x-ms-summary": "Number or records to skip",
            "required": true
          },
          {
            "name": "$top",
            "in": "query",
            "description": "The number of records to return, max = 250",
            "type": "number",
            "x-ms-summary": "Number or records to take",
            "required": true
          },
          {
            "name": "$orderby",
            "in": "query",
            "description": "Field to order by\n[fieldIdentifier] asc/desc",
            "type": "string",
            "x-ms-summary": "The field indentifier to order by in braces [FieldIdentifier]"
          },
          {
            "name": "$filter",
            "in": "query",
            "description": "Provide an oData filter string to filter records by.\nIn the form\n[fieldIdentifier] operation filterValue\nExample\n[textField] eq 'Text'\n\nOperators allowed \nEq\t  Equal\t                        /Suppliers?$filter=[City] eq 'Redmond'\nNe\t  Not equal\t                /Suppliers?$filter=[City] ne 'London'\nGt\t  Greater than\t                /Products?$filter=[Price] gt 20\nGe\t  Greater than or equal\t/Products?$filter=[Price] ge 10\nLt\t  Less than\t                /Products?$filter=[Price] lt 20\nLe\t  Less than or equal\t        /Products?$filter=[Price] le 100\nAnd\t  Logical and\t                /Products?$filter=[Price] le 200 and Price gt 3.5\n",
            "type": "string",
            "x-ms-summary": "Odata filter example [TextField1] eq 'My record'",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "The tenant can be obtained from your system administrator",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response containing an array of records from a report",
            "schema": {
              "$ref": "#/definitions/List-record-response"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      }
    },
    "/Api/Apps/{AppIdentifier}/Data": {
      "post": {
        "description": "Send all field values including defaults when adding a new record to an App",
        "operationId": "Post-a-record",
        "summary": "Create a record",
        "tags": [
          "Data"
        ],
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App, can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "The tenant can be obtained from your system administrator",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "records",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Records"
            },
            "x-ms-summary": "An array of Softools records"
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response contains the record object",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      }
    },
    "/Api/Apps/{AppIdentifier}/Fields": {
      "get": {
        "description": "Get basic field data for an app",
        "operationId": "Get-basic-field-info",
        "summary": "Get basic field info",
        "tags": [
          "Apps"
        ],
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App, can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "Tenant is usually in the site url {tenant}.off.softools.net, however sometimes this is an alias. \nContact systems administrator to confirm it.",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response containing fields that are part of the app",
            "schema": {
              "$ref": "#/definitions/basic-fields-response"
            },
            "examples": {
              "application/json": "{\n  \"identifier\": \"FieldIdentifier\",\n  \"Type\": 1\n}"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      }
    },
    "/Api/Apps/{AppIdentifier}/Data/": {
      "get": {
        "description": "Gets a list of all records from app.\nCan iterate using $top and $skip",
        "operationId": "Get-all-records",
        "summary": "Get all records",
        "tags": [
          "Data"
        ],
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App, can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "$skip",
            "in": "query",
            "description": "Skips records, setting to 1 will return the second record",
            "type": "number",
            "x-ms-summary": "Number or records to skip",
            "required": true
          },
          {
            "name": "$top",
            "in": "query",
            "description": "The number of records to return, max = 250",
            "type": "number",
            "x-ms-summary": "Number or records to take",
            "required": true
          },
          {
            "name": "$orderby",
            "in": "query",
            "description": "Field to order by\n[fieldIdentifier] asc/desc",
            "type": "string",
            "x-ms-summary": "The field indentifier to order by in braces [FieldIdentifier]"
          },
          {
            "name": "$filter",
            "in": "query",
            "description": "Provide an oData filter string to filter records by.\nIn the form\n[fieldIdentifier] operation filterValue\nExample\n[textField] eq 'Text'\n\nOperators allowed \nEq\t  Equal\t                        /Suppliers?$filter=[City] eq 'Redmond'\nNe\t  Not equal\t                /Suppliers?$filter=[City] ne 'London'\nGt\t  Greater than\t                /Products?$filter=[Price] gt 20\nGe\t  Greater than or equal\t/Products?$filter=[Price] ge 10\nLt\t  Less than\t                /Products?$filter=[Price] lt 20\nLe\t  Less than or equal\t        /Products?$filter=[Price] le 100\nAnd\t  Logical and\t                /Products?$filter=[Price] le 200 and Price gt 3.5\n",
            "type": "string",
            "x-ms-summary": "Odata filter example [TextField1] eq 'My record'"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "The tenant can be obtained from your system administrator",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response containing a list of records",
            "schema": {
              "$ref": "#/definitions/List-record-response"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      }
    },
    "/Api/Apps/{AppIdentifier}/Data/{RecordID}/Archived": {
      "delete": {
        "description": "Delete a record. To delete a record you need to archive first.",
        "operationId": "Delete-record",
        "summary": "Delete a record",
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App, can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "RecordID",
            "in": "path",
            "description": "Identifier of the record",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier of the record",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "The tenant can be obtained from your system administrator",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response also includes all record data with field identifier as key",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      }
    },
    "/Api/Apps/{AppIdentifier}/Data/{RecordID}/Unarchive": {
      "post": {
        "description": "Unarchive a record.",
        "operationId": "Unarchived-record",
        "summary": "Unarchive a record",
        "parameters": [
          {
            "name": "AppIdentifier",
            "in": "path",
            "description": "Identifier for the App, can be found in the app Url /App/{AppIdentifier} or /{AppIdentifier}",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier for the App",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "RecordID",
            "in": "path",
            "description": "Identifier of the record",
            "required": true,
            "type": "string",
            "x-ms-summary": "Identifier of the record",
            "x-ms-url-encoding": "single"
          },
          {
            "name": "tenant",
            "in": "header",
            "description": "The tenant can be obtained from your system administrator",
            "required": true,
            "type": "string",
            "x-ms-summary": "The tenant you want to connect too",
            "x-ms-url-encoding": "single"
          }
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Response also includes all record data with field identifier as key",
            "schema": {
              "$ref": "#/definitions/Message"
            }
          },
          "401": {
            "description": "Unauthorized",
            "examples": {
              "application/json": "{\n  \"Message\": \"Authorization has been denied for this request.\"\n}"
            }
          }
        }
      }
    }
  },
  "x-ms-connector-metadata": [
    {
      "propertyName": "Website",
      "propertyValue": "https://www.softools.net"
    },
    {
      "propertyName": "Privacy policy",
      "propertyValue": "https://www.softools.net/privacy-policy"
    },
    {
      "propertyName": "Categories",
      "propertyValue": "Business Intelligence;Data"
    }
  ],
  "definitions": {
    "Message": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      },
      "example": {
        "Message": "string"
      }
    },
    "Records": {
      "type": "object",
      "example": "[\n  {\n    \"TextFieldExample\": \"\",\n    \"DateFieldExample\": null,\n    \"RangeFieldExample\": \"0\",\n    \"MultiStateHarveyBallFieldExample\": \"\",\n    \"MultiStateRAGFieldExample\": \"\",\n    \"BitFieldExample\": false,\n    \"NumberFieldExample\": 0,\n    \"SingleSelectionExample\": \"Item A\",\n    \"ListFieldExample\": {\n      \"changes\": { },\n      \"added\": [ ],\n      \"removed\": [ ]\n    }\n  },\n  {\n    \"TextFieldExample\": \"\",\n    \"DateFieldExample\": null,\n    \"RangeFieldExample\": \"0\",\n    \"MultiStateHarveyBallFieldExample\": \"\",\n    \"MultiStateRAGFieldExample\": \"\",\n    \"BitFieldExample\": false,\n    \"NumberFieldExample \": 0,\n    \"SingleSelectionExample\": \"Item A\",\n    \"ListFieldExample\": {\n      \"changes\": { },\n      \"added\": [ ],\n      \"removed\": [ ]\n    }\n  }\n]"
    },
    "basic-fields-response": {
      "type": "object",
      "properties": {
        "identifier": {
          "type": "string"
        },
        "Type": {
          "type": "integer"
        }
      }
    },
    "List-record-response": {
      "type": "array",
      "items": {},
      "example": [{
        "_id": "id",
        "QuickFilterSearchText": "",
        "Id": "id",
        "EditableAccessForUser": true,
        "Tenant": "",
        "IsArchived": false,
        "TextFieldExample": "Example Text",
        "DateFieldExample ": {
          "$date": 1467331200000
        },
        "RangeFieldExample": "4",
        "MultiStateHarveyBallFieldExample ": "75%",
        "MultiStateRAGFieldExample ": "Amber",
        "BitFieldExample ": true,
        "NumberFieldExample": 20001,
        "SingleSelectionExample": "Item A",
        "ListFieldExample": {
          "changes": {
            "575fbf3cc99d15b138a08324": {
              "TextField2Example": "Item 3"
            }
          },
          "added": [
            {
              "Activity": "Item1",
              "DateField2Example": {
                "$date": 1466208000000
              }
            }
          ],
          "removed": [
            "575fbf3cc99d15b138a08323"
          ]
        }
      }]
    },
    "Record-Response": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "AppIdentifier": {
          "type": "string"
        },
        "CreatedByUserId": {
          "type": "string"
        },
        "CreatedByUser": {
          "type": "string"
        },
        "CreatedDate": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "integer"
            }
          }
        },
        "UpdatedByUserId": {
          "type": "string"
        },
        "UpdatedByUser": {
          "type": "string"
        },
        "UpdatedDate": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "integer"
            }
          }
        },
        "Identifier": {
          "type": "string"
        },
        "QuickFilterSearchText": {
          "type": "string"
        },
        "Id": {
          "type": "string"
        },
        "EditableAccessForUser": {
          "type": "boolean"
        }
      },
      "example": {
        "_id": "id",
        "AppIdentifier": "appIdentifier",
        "CreatedByUserId": "userId",
        "CreatedByUser": "userName",
        "CreatedDate": {
          "$date": 0
        },
        "UpdatedByUserId": "userId",
        "UpdatedByUser": "userName",
        "UpdatedDate": {
          "$date": 0
        },
        "Identifier": "identifier",
        "QuickFilterSearchText": "text",
        "Id": "id",
        "EditableAccessForUser": false,
        "TextFieldExample": "text",
        "RangeFieldExample": 5,
        "MultiStateHarveyBallFieldExample": "75%",
        "MultiStateRAGFieldExample": "Amber",
        "BitFieldExample": false,
        "NumberFieldExample": 0,
        "SingleSelectionExample": "Item 1"
      }
    },
    "Report-Field": {
      "type": "array",
      "items": {},
      "example": [
        {
          "Id": 436108,
          "Identifier": "fieldIdentifier",
          "Type": 11,
          "SubType": 0,
          "Orientation": 1,
          "Label": "fieldLabel",
          "Required": false,
          "Expression": "Expression string",
          "DefaultValue": "",
          "MinValue": 0.1,
          "MaxValue": 6,
          "AutoNumber": false,
          "SelectListIdentifier": "SelectListIdentifier",
          "SelectListSubType": 1,
          "IsTitleField": false,
          "AutoGenerated": false
        }
      ]
    },
    "Update-record": {
      "type": "object",
      "example": "{\n  \"TextFieldExample\": \"text\",\n  \"RangeFieldExample\": 5,\n  \"MultiStateHarveyBallFieldExample\": \"75%\",\n  \"MultiStateRAGFieldExample\": \"Amber\",\n  \"BitFieldExample\": false,\n  \"NumberFieldExample\": 0,\n  \"SingleSelectionExample\": \"Item 1\",\n  \"ListFieldExample\": {\n    \"changes\": {\n      \"575fbf3cc99d15b138a08324\": {\n        \"TextField2Example\": \"Item 3\"\n      }\n    },\n    \"added\": [\n      {\n        \"Activity\": \"Item1\",\n        \"DateField2Example\": {\n          \"$date\": 1466208000000\n        }\n      }\n    ],\n    \"removed\": [\n      \"575fbf3cc99d15b138a08323\"\n    ]\n  }\n}"
    }
  },
  "parameters": {},
  "responses": {},
  "securityDefinitions": {
    "APIKey": {
      "type": "apiKey",
      "in": "header",
      "name": "apikey"
    },
    "Tenant": {
      "type": "apiKey",
      "in": "header",
      "name": "tenant"
    }
  },
  "security": [
    {
      "APIKey": []
    },
    {
      "Tenant": []
    }
  ],
  "tags": []
}