{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "ShipStation IP",
    "description": "The API is a great way to get data directly to and from ShipStation, like creating orders, updating products, and querying order, shipment and customer data.",
    "contact": {
      "name": "ShipStation",
      "url": "https://shipstation.com"
    }
  },
  "host": "ssapi.shipstation.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/stores": {
      "get": {
        "description": "Retrieve the list of installed stores on the account.",
        "tags": [
          "Stores"
        ],
        "operationId": "Stores-Get",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "List stores response.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/StoresResponseItem"
              }
            },
            "examples": {
              "application/json": [
                {
                  "storeId": 22766,
                  "storeName": "ShipStation Manual Store",
                  "marketplaceId": 0,
                  "marketplaceName": "ShipStation",
                  "accountName": null,
                  "email": null,
                  "integrationUrl": null,
                  "active": true,
                  "companyName": "",
                  "phone": "",
                  "publicEmail": "testemail@email.com",
                  "website": "",
                  "refreshDate": "2014-12-03T11:46:11.283",
                  "lastRefreshAttempt": "2014-12-03T11:46:53.433",
                  "createDate": "2014-07-25T11:05:55.307",
                  "modifyDate": "2014-11-12T08:45:20.55",
                  "autoRefresh": false
                },
                {
                  "storeId": 25748,
                  "storeName": "Ashley's Test WooCommerce",
                  "marketplaceId": 36,
                  "marketplaceName": "WooCommerce",
                  "accountName": null,
                  "email": null,
                  "integrationUrl": "http://shipstation.wpengine.com/",
                  "active": true,
                  "companyName": "",
                  "phone": "",
                  "publicEmail": "",
                  "website": "",
                  "refreshDate": "2014-11-26T22:28:14.07",
                  "lastRefreshAttempt": "2014-11-26T14:28:14.07",
                  "createDate": "2014-11-10T08:53:48.077",
                  "modifyDate": "2014-12-03T14:53:50.557",
                  "autoRefresh": true
                }
              ]
            }
          }
        },
        "summary": "List Stores"
      }
    },
    "/stores/marketplaces": {
      "get": {
        "description": "Lists the marketplaces that can be integrated with ShipStation.",
        "tags": [
          "Stores"
        ],
        "operationId": "Stores-Marketplaces-Get",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "List marketplaces response.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/MarketplacesResponseItem"
              }
            },
            "examples": {
              "application/json": [
                {
                  "name": "3DCart",
                  "marketplaceId": 23,
                  "canRefresh": true,
                  "supportsCustomMappings": true,
                  "supportsCustomStatuses": false,
                  "canConfirmShipments": true
                },
                {
                  "name": "Amazon",
                  "marketplaceId": 2,
                  "canRefresh": true,
                  "supportsCustomMappings": true,
                  "supportsCustomStatuses": false,
                  "canConfirmShipments": true
                },
                {
                  "name": "Amazon CA",
                  "marketplaceId": 32,
                  "canRefresh": true,
                  "supportsCustomMappings": true,
                  "supportsCustomStatuses": false,
                  "canConfirmShipments": true
                }
              ]
            }
          }
        },
        "summary": "List Marketplaces"
      }
    },
    "/stores/refreshstore": {
      "post": {
        "description": "Initiates a store refresh.",
        "tags": [
          "Stores"
        ],
        "operationId": "Stores-RefreshStore-Post",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "default": "application/json",
            "description": "Content type.",
            "x-ms-summary": "Content Type",
            "x-ms-visibility": "internal"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RefreshStoreRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Refresh store response.",
            "schema": {
              "$ref": "#/definitions/RefreshStoreResponse"
            },
            "examples": {
              "application/json": {
                "success": true,
                "message": "A store refresh has been initiated for Store ID 12345"
              }
            }
          }
        },
        "summary": "Refresh Store"
      }
    }
  },
  "definitions": {
    "MarketplacesResponseItem": {
      "title": "List Marketplaces Response Item",
      "example": {
        "name": "3DCart",
        "marketplaceId": 23,
        "canRefresh": true,
        "supportsCustomMappings": true,
        "supportsCustomStatuses": false,
        "canConfirmShipments": true
      },
      "type": "object",
      "properties": {
        "name": {
          "example": "3DCart",
          "type": "string"
        },
        "marketplaceId": {
          "example": 23,
          "type": "integer",
          "format": "int32"
        },
        "canRefresh": {
          "example": true,
          "type": "boolean"
        },
        "supportsCustomMappings": {
          "example": true,
          "type": "boolean"
        },
        "supportsCustomStatuses": {
          "example": false,
          "type": "boolean"
        },
        "canConfirmShipments": {
          "example": true,
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "marketplaceId",
        "canRefresh",
        "supportsCustomMappings",
        "supportsCustomStatuses",
        "canConfirmShipments"
      ]
    },
    "StoresResponseItem": {
      "title": "List Stores Response Item",
      "example":  {
        "storeId": 22766,
        "storeName": "ShipStation Manual Store",
        "marketplaceId": 0,
        "marketplaceName": "ShipStation",
        "accountName": null,
        "email": null,
        "integrationUrl": null,
        "active": true,
        "companyName": "",
        "phone": "",
        "publicEmail": "testemail@email.com",
        "website": "",
        "refreshDate": "2014-12-03T11:46:11.283",
        "lastRefreshAttempt": "2014-12-03T11:46:53.433",
        "createDate": "2014-07-25T11:05:55.307",
        "modifyDate": "2014-11-12T08:45:20.55",
        "autoRefresh": false
      },
      "type": "object",
      "properties": {
        "storeId": {
          "example": 22766,
          "type": "integer",
          "format": "int32"
        },
        "storeName": {
          "example": "ShipStation Manual Store",
          "type": "string"
        },
        "marketplaceId": {
          "example": 0,
          "type": "integer",
          "format": "int32"
        },
        "marketplaceName": {
          "example": "ShipStation",
          "type": "string"
        },
        "accountName": {},
        "email": {},
        "integrationUrl": {},
        "active": {
          "example": true,
          "type": "boolean"
        },
        "companyName": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "publicEmail": {
          "example": "testemail@email.com",
          "type": "string"
        },
        "website": {
          "type": "string"
        },
        "refreshDate": {
          "example": "2014-12-03T11:46:11.283"
        },
        "lastRefreshAttempt": {
          "example": "2014-12-03T11:46:53.433"
        },
        "createDate": {
          "example": "2014-07-25T11:05:55.307",
          "type": "string"
        },
        "modifyDate": {
          "example": "2014-11-12T08:45:20.55",
          "type": "string"
        },
        "autoRefresh": {
          "example": false,
          "type": "boolean"
        }
      },
      "required": [
        "storeId",
        "storeName",
        "marketplaceId",
        "marketplaceName",
        "active",
        "companyName",
        "phone",
        "publicEmail",
        "website",
        "refreshDate",
        "lastRefreshAttempt",
        "createDate",
        "modifyDate",
        "autoRefresh"
      ]
    },
    "RefreshStoreRequest": {
      "title": "Refresh Store Request",
      "example": {
        "storeId": 12345,
        "refreshDate": "2020-05-29 15:05:02"
      },
      "type": "object",
      "properties": {
        "storeId": {
          "type": "integer",
          "format": "int32"
        },
        "refreshDate": {
          "type": "string"
        }
      }
    },
    "RefreshStoreResponse": {
      "title": "Refresh Store Response",
      "example": {
        "success": true,
        "message": "A store refresh has been initiated for Store ID 12345"
      },
      "type": "object",
      "properties": {
        "success": {},
        "message": {
          "type": "string"
        }
      },
      "required": [
        "success",
        "message"
      ]
    }
  },
  "securityDefinitions": {
    "auth": {
      "type": "basic"
    }
  },
  "tags": [
    {
      "name": "Stores"
    }
  ],
  "x-ms-connector-metadata": [
    {
      "propertyName": "Website",
      "propertyValue": "https://shipstation.com"
    },
    {
      "propertyName": "Privacy policy",
      "propertyValue": "https://shipstation.com/privacy-policy"
    },
    {
      "propertyName": "Categories",
      "propertyValue": "Business Management"
    }
  ]
}